pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from repository (Assuming git)
                echo 'Checking out code...'
                // git 'https://github.com/your-repo/stationery-management-system.git'
            }
        }
        
        stage('Build & Test') {
            steps {
                echo 'Building and running Unit Tests...'
                dir('backend') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Building Docker Images...'
                dir('ci-cd') {
                    bat 'docker-compose build'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying containers using Docker Compose...'
                dir('ci-cd') {
                    bat 'docker-compose up -d'
                }
            }
        }
    }
}
